---
title: "aaR - Intro"
date: "`r format(Sys.Date(), '%d-%b-%Y')`"
output: 
  github_document:
     toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(aaR)

load("C:/Constantine/Research/R/R - Packages/aaR/tests/data/data3.RData")
data <- data3
```

Examples of model portfolios based on `aaR` package.

***

### 01 - Simple Allocation

```{r aar01}

res <- portfolio_returns(prices = data, method = "none", name = "01 - simple portfolio")
res

```


### 02 - Calendar Rebalancing

```{r aar02}

res <- portfolio_returns(prices = data, method = "calendar",
                         period = "quarters2", weights = c(0.3,0.3,0.4), 
                         slippage = 0.15/100, name = "02 - simple portfolio")
res

```

### 03 - Sell May


```{r aar03}

data01 <- data[,c("SPY","TLT")]

wts <- alternate_weights(prices = data01, 
                         weights = matrix(c(0.5, 0.5, 1, 0), nrow = 2, byrow = TRUE),
                         months = c("May", "Oct"))

head(wts)

res <- portfolio_returns(prices = data01, weights = wts,  method = "irregular",
                         slippage = 0.15/100, name = "03 - sell may portfolio")

summary(obj = res, bkm = data01[,1], .name = "Sell May")
```

```{r aar03b, echo = FALSE, fig.width=10}

x <- cbind(res$main,data01[,1])
colnames(x) <- c("sellmay", "spy")

melt_xts_month(x) %>% gg_line_maxdd() + theme_sb_base()

```



### 04 - All Calendar Periods

```{r aar04}

pd <-c("weeks", "months", "quarters", "quarters2", "semi-annual", "years")

res <- purrr::map(pd, ~portfolio_returns(prices = data, method = "calendar",
                         period = .x, weights = c(0.3,0.3,0.4), 
                         slippage = 0.15/100, name = .x)) %>% setNames(.,pd)

```

```{r aar04b, echo=FALSE}
out <- purrr::map2(res, names(res),~summary(obj =.x,.name = .y))
out <-  Reduce(function(...){left_join(..., by = "statistic")}, x = out)

knitr::kable(out)
```

